# CI Tool (https://app.travis-ci.com/)
language: generic

# Super user level permission
sudo: required

# We need a copy of docker running
services:
    - docker

# Commands to be executed before running tests or deploying the project
before_install:
    # build image using Dockerfile.dev
    - docker build -t rawanad/docker-react -f Dockerfile.dev .

# Commands to be executed to run the test suite
script:
    # -- --coverage: automatically exits when the test suite is done
    #- docker run rawanad/docker-react npm run test -- --coverage
    - docker run -e CI=true rawanad/docker-react npm run test

# Deploy app tp AWS
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    # name specified on AWS
    app: 'docker-react'
    # environment specified on AWS
    env: 'Dockerreact-env'
    # in servies, search for S3 and choose the bucket based on location
    bucket_name: 'elasticbeanstalk-us-east-1-609456652928'
    # app name
    bucket_path: 'docker-react'
    # deploy when I push code to branch master
    on:
        branch: master
    # Keys defined on Travis
    access_key_id: $AWS_ACCESS_KEY
    #secret_access_key:
    #    secure: '$AWS_SECRET_KEY'
    secret_access_key: $AWS_SECRET_KEY
