# Docker file for development environment only
# Create an image that can be used in the development environment

# We need a specific version of Node to avoid bugs
#FROM node:16-alpine

#WORKDIR '/app'

## Copy package.json to the current working directory (app)
#COPY package.json .
#RUN npm install

## Copy everything to working directory
#COPY . .

## Same as npm start
#CMD ["npm", "run", "start"]

# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/18799500#questions/14297316
FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "start"]